const Messages = {
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    USER_NOT_FOUND: "User with this email doesn't exist",
    OTP_EXPIRY: "Your OTP has expired",
    INVALID_OTP: "OTP is not valid",
    INVALID_EMAIL: "Please enter a valid email",
    PASSWORD_LENGTH: "Your password must be at least 8 characters long",
    PASSWORD_LETTER: "Your password must contain at least one letter",
    PASSWORD_DIGIT: "Your password must contain at least one number",
    PASSWORD_SPECIALCHAR: "Your password must contain at least one special character",
    ACCOUNT_NOT_FOUND: "User with this credentials doesn't exist",
    TOKEN_EXPIRED: "Password reset link has been expired",
    PROFILE_ALREADY_EXIST: "Profile for this user already exist",
    PROFILE_NOT_FOUND: "Profile for this user doesn't exist",
    ACCESS_NOT_ALLOWED: "Access denied, No token provided",
    JWT_TOKEN_EXPIRED: "Authentication token has expired",
    INVALID_TOKEN: "Token is invalid",
    NO_TOKEN: "No token provided",
    CLASS_EXIST: "Class already exist",
    CLASS_NOT_FOUNT: "Class doesn't exist",
    SUBJECT_EXIST: "Subject already exist",
    ATTENDANCE_ALREADY_EXIST: "Attendance already exist",
    ROLL_EXIST: "Roll number already exist",
    ATTENDANCE_NOT_FOUND: "Attendance not found",
    SCHOOL_NOT_FOUND: "School not found",
    PASSWORD_CHANGE_NOT_ALLOWED: "Password change is not allowed for Google accounts",
    ASSIGNMENT_NOT_FOUND: "Assignment doesn't exist.",
    STUDY_MATERIAL_NOT_FOUND: "Assignment doesn't exist.",
    ASSIGNMENT_SUBMISSION_NOT_FOUND: "Assignment submission doesn't exist.",
    ANNOUNCEMENT_NOT_FOUND: "Assignment submission doesn't exist.",
    ANNOUNCEMENT_PIN_LIMIT: "Pinning more than two announcements is not allowed"
  };

  export default Messages