const Messages = {
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    USER_NOT_FOUND: "User with this email doesn't exist",
    OTP_EXPIRY: "Your OTP has expired",
    INVALID_OTP: "OTP is not valid",
    INVALID_EMAIL: "Please enter a valid email",
    PASSWORD_LENGTH: "Your password must be at least 8 characters long",
    PASSWORD_LETTER: "Your password must contain at least one letter",
    PASSWORD_DIGIT: "Your password must contain at least one number",
    PASSWORD_SPECIALCHAR: "Your password must contain at least one special character",
    ACCOUNT_NOT_FOUND: "User with this credentials doesn't exist",
    TOKEN_EXPIRED: "Password reset link has been expired",
    PROFILE_ALREADY_EXIST: "Profile for this user already exist",
    PROFILE_NOT_FOUND: "Profile for this user doesn't exist",
    ACCESS_NOT_ALLOWED: "Access denied, No token provided",
    JWT_TOKEN_EXPIRED: "Authentication token has expired",
    INVALID_TOKEN: "Token is invalid",
    NO_TOKEN: "No token provided",
    CLASS_EXIST: "Class already exist",
    CLASS_NOT_FOUNT: "Class doesn't exist",
    SUBJECT_EXIST: "Subject already exist",
    SUBJECT_NOT_FOUND: "Subject not found",
    ATTENDANCE_ALREADY_EXIST: "Attendance already exist",
    ROLL_EXIST: "Roll number already exist",
    ATTENDANCE_NOT_FOUND: "Attendance not found",
    SCHOOL_NOT_FOUND: "School not found",
    PASSWORD_CHANGE_NOT_ALLOWED: "Password change is not allowed for Google accounts",
    ASSIGNMENT_NOT_FOUND: "Assignment doesn't exist.",
    STUDY_MATERIAL_NOT_FOUND: "Assignment doesn't exist.",
    ASSIGNMENT_SUBMISSION_NOT_FOUND: "Assignment submission doesn't exist.",
    ANNOUNCEMENT_NOT_FOUND: "Assignment submission doesn't exist.",
    ANNOUNCEMENT_PIN_LIMIT: "Pinning more than two announcements is not allowed",
    INVOICE_NOT_FOUND: "Invoice not found",
    LEAVELETTER_NOT_FOUND: "Leave letter not found",
    CONVERSATION_NOT_FOUND: "Conversation not found",
    EXAM_NOT_FOUND: "Exam not found",
    EXAMRESULT_NOT_FOUND: "Exam result not found",
    SUBSCRIPTION_NOT_FOUND: "Subscription not found",
    TIMETABLE_NOT_FOUND: "Timetable not found",
    PLAN_NOT_FOUND: "Plan not found",
    MESSAGE_NOT_FOUND: "Message not found",
    CANNOT_DELETE_MESSAGE: "You do not have access to delete this message",
    SUBSCRIPTION_ALREADY_EXISTS: "You already have subscribed to a plan",
    CANNOT_DELETE_CONVERSATION: "You do not have access to delete tis conversation",
    ACADEMIC_YEAR_EXIST: "Academic year for this school already exist",
    ACTIVE_ACADEMIC_YEAR_NOT_FOUND: "No active academic year found for this school",
    NOTIFICATION_NOT_FOUND: "Notification not found",
    INVALID_MESSAGE_DATA: "Invalid message data provided",
    INVALID_DATE_RANGE: "Invalid date range provided. 'fromDate' must be before 'toDate'.",
    PAST_DATE_NOT_ALLOWED: "Past dates are not allowed for leave letters.",
    DUE_DATE_INVALID: "Due date must be after the current date.",
    CHAPTER_NOT_FOUND: "Chapter not found",
    STUDENT_ALREADY_EXIST: "Student is already part of a class"
  };

  export default Messages